import PreventiveCoverage from './PreventiveCoverage'
import {useEffect,useState} from 'react'

export default function PreventiveChecklist({row,currentUser,request,onSaved}){
  const data=row.request_data.preventive
  const [items,setItems]=useState(data.items),[participants,setParticipants]=useState(data.participants||[]),[revision,setRevision]=useState(data.revision)
  const [users,setUsers]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false)
  const editable=row.status==='EN_PROCESO'&&Number(row.assigned_to)===Number(currentUser.id)
  useEffect(()=>{if(!dirty){setItems(data.items);setParticipants(data.participants||[]);setRevision(data.revision)}},[data.revision,dirty])
  useEffect(()=>{if(editable)request('/preventivos/personal').then(setUsers).catch(e=>setError(e.message))},[editable])
  async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await request(`/preventivos/solicitudes/${row.id}/checklist`,{method:'PUT',body:JSON.stringify({revision,items:items.map(({key,status,notes})=>({key,status,notes})),participants:participants.map(p=>({user_id:Number(p.user_id),minutes:Number(p.minutes)}))})});setDirty(false);onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
  function changePoint(index,key,value){setDirty(true);setItems(rows=>rows.map((r,i)=>i===index?{...r,[key]:value}:r))}
  return <section className="request-detail"><h3>Checklist preventivo{data.route?` · ${data.route}`:''}</h3><p>{data.element_name} · Vencimiento: {data.due}</p><PreventiveCoverage machines={data.machines}/><p style={{whiteSpace:'pre-wrap'}}>{data.procedure}</p>{data.reference&&<p>Referencia: {data.reference}</p>}{data.skipped_cycles>0&&<p>Incluye {data.skipped_cycles} ciclos atrasados adicionales sin ejecución registrada.</p>}{error&&<p role="alert">{error}</p>}{dirty&&revision!==data.revision&&<p role="alert">Existe una versión más reciente. Actualiza la solicitud antes de guardar.</p>}<form onSubmit={save}><fieldset disabled={!editable||busy} className="request-fields">{items.map((point,index)=><div className="preventive-point" key={point.key}><strong>{point.name}</strong><p>{[point.bearing_code&&`Rodamiento: ${point.bearing_code}`,point.housing_code&&`Chumacera: ${point.housing_code}`,point.lubricant,point.dose].filter(Boolean).join(' · ')}</p><div className="motor-form-grid"><label>Resultado<select value={point.status} onChange={e=>changePoint(index,'status',e.target.value)}><option value="PENDIENTE">Pendiente</option><option value="REALIZADO">Realizado</option><option value="NO_REALIZADO">No realizado</option></select></label><label>Observaciones / motivo{point.status==='NO_REALIZADO'?' *':''}<textarea required={point.status==='NO_REALIZADO'} maxLength={1000} value={point.notes} onChange={e=>changePoint(index,'notes',e.target.value)}/></label></div></div>)}<h4>Participantes y tiempo real</h4>{participants.map((p,index)=><div className="motor-form-grid" key={index}><label>Participante *<select required value={p.user_id} onChange={e=>{setDirty(true);setParticipants(list=>list.map((v,i)=>i===index?{...v,user_id:Number(e.target.value)}:v))}}><option value="">Selecciona</option>{!users.some(u=>u.id===p.user_id)&&p.user_id&&<option value={p.user_id}>{p.name||`Usuario ${p.user_id}`}</option>}{users.map(u=><option key={u.id} value={u.id}>{u.nombre_completo||u.nombre}</option>)}</select></label><label>Minutos reales *<input required type="number" min="1" max="525600" value={p.minutes} onChange={e=>{setDirty(true);setParticipants(list=>list.map((v,i)=>i===index?{...v,minutes:e.target.value}:v))}}/></label><button type="button" onClick={()=>{setDirty(true);setParticipants(list=>list.filter((_,i)=>i!==index))}}>Quitar participante</button></div>)}{editable&&<><button type="button" onClick={()=>{setDirty(true);setParticipants(list=>[...list,{user_id:list.length?'':currentUser.id,minutes:'',name:currentUser.nombre_completo||currentUser.nombre}])}}>Agregar participante</button><div className="modal-actions"><button className="primary-action">{busy?'Guardando…':'Guardar checklist'}</button></div></>}</fieldset></form><p className="field-help">Antes de entregar, registra cada punto y los participantes. Los repuestos y consumos se registran en la entrega habitual.</p></section>
}
